### ISSUE TITLE
Need support for Chinese characters

### ISSUE THREAD

**Issue by Sapph1reX** [glutanimate/pdf-glossary#7]
I began using this fantastic add-on today and I found it really helpful as to preparing for exams. However, when exported, Chinese characters become black boxes and are utterly indistinguishable. Since I'm a Chinese student, Chinese support really matters. Could you please manage to add this function in the near future?

**Comment by Sapph1reX** [comment]
I began using this fantastic add-on today and I found it really helpful as to preparing for exams. However, when exported, Chinese characters become black boxes and are utterly indistinguishable. Since I'm a Chinese student, Chinese support really matters. Could you please manage to add this function in the near future?

**Comment by zwei2stein** [comment]
It needs mroe than that, it is likely missing support of UTF-8

It also misses some lain character with accents (letters from "Příliš žluťoučký kůň úpěl ďábelské ódy") and japanese characters (あえいおう、アエイオウ).

**Comment by glutanimate** [comment]
Please see here: #3
